Code book for Analysis
========================================================

Variable description for data
--------------------------------------------------------

This convention was adapted from the codebook used for the data set in the quizzes for this course.

```{r echo=FALSE}
source("run_analysis.R")
a <- paste("subject","\t",2,sep="")
aa <- paste("\t\t","1-30","Subject Id",sep=" ")
aaa <- paste(a,aa,sep="\n")
b <- paste("activity","\t",1,sep="")
bb <- paste("\t\t","1-6","Activity",sep=" ")
bbb <- paste("\t\t\t\t",1:6," ",c("WALKING","WALKING_UPSTAIRS","WALKING_DOWNSTAIRS","SITTING","STANDING","LAYING"),sep="")
bbbb <- cat(b,bb,bbb,sep="\n")
c <- paste(names(tidyData)[-c(1,2)],"\t",7,sep="")
d <- paste("\t\t","Real number  ",VariableDescription[-c(1,2)],sep="")
cat(aaa,bbbb,paste(c,d,sep="\n"),sep="\n\n")

```

Steps taken to clean up data
-----------------------------------------------------------

### Read the training data
* Read in the "X_train.txt" data
* Read in the "subject_train.txt" data
* Read in the "y_train.txt" data
* Create a training data set by merging subject, X and y

### Read the testing data
* Read in the "X_test.txt" data
* Read in the "subject_test.txt" data
* Read in the "y_test.txt" data
* Create a testing data set by merging subject, X and y

### Merge the training and testing data sets

### Set activity and initial variable names
* Read the activity data and features data
* Use activity names to name the activities in the data
* Use feature names to name the activities in the data
* Extract only the measurements or variables having mean or standard deviation in the features -- this gives a total of 66 variables; with the subject and activity variables makes a total of 68 variables in the data
* Modify the variable labels in the data set to have a good descriptive variable or feature names
* Create independent tidy data set by aggregating data with the average of each variable for activity and subject  




















